### ISSUE TITLE
Error: Double time specification

### ISSUE THREAD

**Issue by stojko75** [jwcobb/tevo-harvester#16]
I started to receive this error:
```

/vendor/tevoharvester/artisan harvester:update events --action=active
Updating active events 100 at a time


  [Exception]
  DateTime::__construct(): Failed to parse time string (201608-12-09T20:00:00Z) at position 12 (T): Double time specification

/vendor/tevoharvester/artisan harvester:update events --action=active
Updating active events 100 at a time


  [Exception]
  DateTime::__construct(): Failed to parse time string (201608-12-09T20:00:00Z) at position 12 (T): Double time specification
```

**Comment by stojko75** [comment]
Please could you fix this error? Here's the log, and as I can see, the date format is wrong and script cannot parse it. It says, at two places, 201608-12-09T20:00:00-06:00 and I think it should 2016-08-12-09T20:00:00-06:00. 

performers/5492\",\"name\":\"Janet Jackson\"},\"primary\":true}]},{\"id\":1091386,\"url\":\"/events/1091386\",\"name\":\"Magic Men Live!\",\"state\":\"shown\",\"occurs_at\":\"201608-12-09T20:00:00Z\",\"occurs_at_local\":\"201608-12-09T20:00:00-06:00\",\"updated_at\":\"2016-10-27T20:36:16Z\",\"notes\":\"\",\"owned_by_office\":false,\"products_count\":0,\"products_eticket_count\":0,\"available_count\":0,\"category\":{\"id\":\"87\",\"name\":\"Miscellaneous\",\"slug\":\"miscellaneous\",\"url\":\"/categories/87\",\"slug_url\":\"/categories/miscellaneous\",\"parent\":{\"id\":\"54\",\"name\":\"Concerts\",\"slug\":\"concerts\",\"url\":\"/categories/54\",\"slug_url\":\"/categories/concerts\",\"parent\":null}},\"popularity_score\":0.0,\"long_term_popularity_score\":0.0,\"stubhub_id\":null,\"configuration\":{\"id\":38104,\"url\":\"/configurations/38104\",\"name\":\"General Admission\",\"fanvenues_key\":null,\"ticket_utils_id\":null,\"seating_chart\":{\"medium\":\"https://s3.amazonaws.com/media.ticketevolution.com/configurations/default_maps/ga_500.jpg\",\"large\":\"https://s3.amazonaws.com/media.ticketevolution.com/configurations/default_maps/ga_1000.jpg\"}},\"venue\":{\"id\":30567,\"slug\":\"aztec-theater\",\"url\":\"/venues/30567\",\"slug_url\":\"/venues/aztec-theater\",\"name\":\"Aztec Theater\",\"location\":\"San Antonio, TX\",\"time_zone\":null},\"performances\":[{\"performer\":{\"id\":46441,\"slug\":\"magic-men-live\",\"slug_url\":\"/performers/magic-men-live\",\"url\":\"/performers/46441\",\"name\":\"Magic Men LIVE\"},\"primary\":true}]}]})"} []
[2016-11-21 18:54:59] local.ERROR: exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (201608-12-09T20:00:00Z) at position 12 (T): Double time specification' in /home/zeronosebleeds/vendor/tevoharvester/vendor/nesbot/carbon/src/Carbon/Carbon.php:221 Stack trace: #0 /home/zeronosebleeds/vendor/tevoharvester/vendor/nesbot/carbon/src/Carbon/Carbon.php(221): DateTime->__construct('201608-12-09T20...', Object(DateTimeZone)) #1 /home/zeronosebleeds/vendor/tevoharvester/app/Tevo/Event.php(136): Carbon\Carbon->__construct('201608-12-09T20...') #2 [internal function]: TevoHarvester\Tevo\Event::storeFromApi(Array) #3 /home/zeronosebleeds/vendor/tevoharvester/app/Jobs/UpdateResourceJob.php(59): call_user_func('TevoHarvester\\T...', Array) #4 [internal function]: TevoHarvester\Jobs\UpdateResourceJob->handle(Object(TicketEvolution\Laravel\TEvoFacade)) #5 /home/zeronosebleeds/vendor/tevoharvester/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array) #6 /home/zeronosebleeds/vendor/tevoharvester/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(82): Illuminate\Container\Container->call(Array) #7 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(TevoHarvester\Jobs\UpdateResourceJob)) #8 /home/zeronosebleeds/vendor/tevoharvester/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(TevoHarvester\Jobs\UpdateResourceJob)) #9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(TevoHarvester\Jobs\UpdateResourceJob)) #10 /home/zeronosebleeds/vendor/tevoharvester/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(TevoHarvester\Jobs\UpdateResourceJob)) #11 /home/zeronosebleeds/vendor/tevoharvester/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(83): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #12 /home/zeronosebleeds/vendor/tevoharvester/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(69): Illuminate\Bus\Dispatcher->dispatchNow(Object(TevoHarvester\Jobs\UpdateResourceJob)) #13 /home/zeronosebleeds/vendor/tevoharvester/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(TevoHarvester\Jobs\UpdateResourceJob)) #14 /home/zeronosebleeds/vendor/tevoharvester/app/Console/Commands/UpdateResourceCommand.php(103): TevoHarvester\Console\Commands\UpdateResourceCommand->dispatch(Object(TevoHarvester\Jobs\UpdateResourceJob)) #15 /home/zeronosebleeds/vendor/tevoharvester/app/Console/Commands/UpdateResourceCommand.php(60): TevoHarvester\Console\Commands\UpdateResourceCommand->handleUpdate() #16 [internal function]: TevoHarvester\Console\Commands\UpdateResourceCommand->handle() #17 /home/zeronosebleeds/vendor/tevoharvester/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array) #18 /home/zeronosebleeds/vendor/tevoharvester/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array) #19 /home/zeronosebleeds/vendor/tevoharvester/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)

**Comment by jwcobb** [comment]
This looks like a bug in the API response, not with this library.

Can you tell me how you got this response? I am unable to reproduce.

**Comment by stojko75** [comment]
When client tried to buy tickets yesterday on site first time with American
Express and today with VISA he alarmed us. Today I tried with no success.
You can try to buy tickets from our site as well.
https://zeronosebleeds.com

I checked code several times and everything looks ok. However during
process of creating order at TiEvo, api return error at credit_card
endpoint.

I sent to you entity debug from our site.

**Comment by jwcobb** [comment]
Sounds like you are referring to something different than this error.

**Comment by stojko75** [comment]
Yes, sorry I received other email from you regarding credit_card issue and
didn't notice you are talking about this.
This issue is produced during sync with TE by tevoharvester.
